### ISSUE TITLE
[seu.services] About 指向的 URL 错误

### ISSUE THREAD

**Issue by higuoxing** [SEU-ITE/SEU-ITE.github.io#1]
不太清楚在这里留 Issue 是否合适，[seu.service](https://www.seu.services/) About 页面指向的页面应该为 [https://seuite.github.io/](https://seuite.github.io/)

**Comment by encofcomic** [comment]
已修正，感谢指正

**Comment by c4yg70** [comment]
已修正，感谢指正。
